# Generated by Django 5.0.3 on 2024-04-02 17:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255, verbose_name='UserName')),
                ('FirstName', models.CharField(max_length=255, verbose_name='FirstName')),
                ('LastName', models.CharField(max_length=255, verbose_name='LastName')),
                ('Email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
