# Generated by Django 5.0.3 on 2024-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='users_info',
            name='LastName',
            field=models.CharField(blank=True, max_length=255, verbose_name='LastName'),
        ),
    ]
