# Generated by Django 5.0.3 on 2024-03-31 11:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone'),
        ),
    ]
