# Generated by Django 5.0.3 on 2024-03-31 11:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_info_email_alter_users_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
    ]
