version: '1.1'
services:
  flask_web:
    container_name: otus_result_homework
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgres_otus_container
    image: postgres:14
    volumes:
       - flaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-qlik@ivan-shamaev.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-A->V9>pS6HJ~xY8d}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - backend
volumes:
    flaskdb:
      driver: local
    pgadmin:
      driver: local
networks:
  backend:
    driver: bridge