apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metrics
  labels:
    app: metrics
spec:
    replicas: 2
    selector:
       matchLabels:
          app: metrics
    template:
       metadata:
          labels:
            app: metrics
       spec:
          containers:
          - name: metrics
            image: metrics:v2
            ports:
              - containerPort: 8090

