apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-project-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /OTUS_Project/(.*)
            pathType: Prefix
            backend:
              service:
                name: otus-project-app
                port:
                  name: http

