apiVersion: batch/v1
kind: Job
metadata:
  name: otus-project-app-db-migrations
  namespace: otus-project-app
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 60

  template:
    spec:
      containers:
        - name: migration-container
          image: rooover/otus_app_django_46:13
          command: ['python','manage.py','migrate']
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                    name: app-cm
          ports:
            - containerPort: 8000
      restartPolicy: OnFailure
  backoffLimit: 15