apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-project-app
  namespace: otus-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-project-app
      env: prod
  template:
    metadata:
      labels:
        app: otus-project-app
        env: prod

    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      containers:
        - name: otus-project-app
          image: rooover/otus_app_django_46:13
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - mountPath: "/data/static"
              name: staticfiles

