apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXdtZ2JhbzUpZyN5Xzcha3IzdSZrczleOXEqYW5qKGxkZWNqYWU4KiFtc294ZW03IXB4
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNDQzMjE=
