# Generated by Django 5.0.3 on 2024-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Message'),
        ),
    ]
