# Generated by Django 5.0.3 on 2024-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('RawID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(blank=True, null=True, verbose_name='Product_id')),
                ('Counts_product', models.IntegerField(blank=True, null=True, verbose_name='Counts_product')),
                ('Is_booking', models.BooleanField(default=False)),
                ('User_id', models.IntegerField(blank=True, null=True, verbose_name='UserID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
