# Generated by Django 5.0.3 on 2024-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False, verbose_name='OrderID')),
                ('UserName', models.CharField(max_length=255, verbose_name='UserName')),
                ('UserID', models.IntegerField(blank=True, null=True, verbose_name='UserID')),
                ('Product_id', models.IntegerField(blank=True, null=True, verbose_name='Product_id')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='DateTime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
