# Generated by Django 5.0.3 on 2024-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_info',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
