# Generated by Django 5.0.3 on 2024-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False, verbose_name='OrderID')),
                ('UserName', models.CharField(max_length=255, verbose_name='UserName')),
                ('UserID', models.IntegerField(blank=True, null=True, verbose_name='UserID')),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('IsPayed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
